export let TYPES = {
    IActionDispatcher: Symbol('IActionDispatcher'),
    IActionDispatcherProvider: Symbol('IActionDispatcherProvider'),
    ActionHandlerRegistry: Symbol('ActionHandlerRegistry'),
    IAnimationFrameSyncer: Symbol('IAnimationFrameSyncer'),
    ICommand: Symbol('ICommand'),
    ICommandStack: Symbol('ICommandStack'),
    ICommandStackProvider: Symbol('ICommandStackProvider'),
    IDiagramServer: Symbol('IDiagramServer'),
    KeyListener: Symbol('KeyListener'),
    ILogger: Symbol('ILogger'),
    LogLevel: Symbol('LogLevel'),
    IModelFactory: Symbol('IModelFactory'),
    MouseListener: Symbol('MouseListener'),
    IViewer: Symbol('IViewer'),
    IViewerOptions: Symbol('IViewerOptions'),
    IViewerProvider: Symbol('IViewerProvider'),
    ViewRegistry: Symbol('ViewRegistry'),
    VNodeDecorator: Symbol('VNodeDecorator'),
}
