export const TYPES = {
    IActionDispatcher: Symbol('IActionDispatcher'),
    IActionDispatcherProvider: Symbol('IActionDispatcherProvider'),
    ActionHandlerRegistry: Symbol('ActionHandlerRegistry'),
    AnimationFrameSyncer: Symbol('AnimationFrameSyncer'),
    ICommand: Symbol('ICommand'),
    ICommandStack: Symbol('ICommandStack'),
    ICommandStackProvider: Symbol('ICommandStackProvider'),
    HoverState: Symbol('HoverState'),
    KeyListener: Symbol('KeyListener'),
    ILogger: Symbol('ILogger'),
    LogLevel: Symbol('LogLevel'),
    IModelFactory: Symbol('IModelFactory'),
    ModelRendererFactory: Symbol('ModelRendererFactory'),
    ModelSource: Symbol('ModelSource'),
    SModelStorage: Symbol('SModelStorage'),
    MouseListener: Symbol('MouseListener'),
    PopupMouseListener: Symbol('PopupMouseListener'),
    IViewer: Symbol('IViewer'),
    ViewerOptions: Symbol('ViewerOptions'),
    IViewerProvider: Symbol('IViewerProvider'),
    ViewRegistry: Symbol('ViewRegistry'),
    IVNodeDecorator: Symbol('IVNodeDecorator'),
    HiddenVNodeDecorator: Symbol('HiddenVNodeDecorator'),
    PopupVNodeDecorator: Symbol('PopupVNodeDecorator')
}
